// <auto-generated />
using System;
using FinancialHelper.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialHelper.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230705120708_profile")]
    partial class profile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("FinancialHelper.Entities.BankData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoAfterTransaction")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional1")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional3")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional4")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional5")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional6")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDescriptionAdditional7")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("BankDatas");
                });

            modelBuilder.Entity("FinancialHelper.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialHelper.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinancialHelper.Entities.BankData", b =>
                {
                    b.HasOne("FinancialHelper.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FinancialHelper.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
